openapi: 3.0.3
info:
  title: Cadastro de Aplicativo API
  version: 1.0.0
  description: |
    API para suportar a jornada de cadastro de aplicativo, incluindo criação, atualização, consulta e remoção de aplicativos.
  contact:
    name: Suporte Técnico
    email: suporte@empresa.com.br
    url: https://empresa.com.br/suporte
tags:
  - name: Aplicativos
    description: Operações relacionadas ao cadastro e gerenciamento de aplicativos
  - name: Imagens
    description: Operações relacionadas ao upload de imagens
servers:
  - url: http://localhost:3000/api
    description: Servidor local de desenvolvimento

paths:
  /apps:
    post:
      tags: [Aplicativos]
      summary: Criar cadastro de aplicativo (draft)
      description: |
        Cria um novo cadastro de aplicativo em estado draft/pendente, já registrando os metadados das imagens (hash, tamanho, content-type).
        Retorna as URLs de upload para cada imagem. O cadastro só será considerado completo após todos os uploads.
      operationId: criarCadastroAplicativo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppDraftInput'
            examples:
              exemplo:
                summary: Exemplo de criação draft
                value:
                  nome: Meu App
                  descricao: Aplicativo para gestão de vendas
                  codigoParceiro: parceirinho-123
                  codigoProduto: prod-xyz
                  contatoParceiro:
                    nome: Suporte App
                    email: suporte@meuapp.com
                    telefone: '+55 11 99999-9999'
                    descricao: Canal oficial de suporte
                  categorias: ['cat-1', 'cat-2']
                  configuracoes:
                    - nomePacoteApp: com.meuapp.vendas
                      tipoIntegracaoId: integracao-1
                      terminalModeloId: modelo-1
                  detalheAplicativo:
                    descricao: App para vendas em campo
                    imagens:
                      - nomeArquivo: logo.png
                        tipoMime: image/png
                        tamanho: 123456
                        md5: 'abc123def456'
                      - nomeArquivo: banner.jpg
                        tipoMime: image/jpeg
                        tamanho: 654321
                        md5: 'xyz789uvw000'
      responses:
        '201':
          description: Cadastro criado em estado draft. URLs de upload geradas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppDraftResponse'

  /apps/{id}:
    get:
      tags: [Aplicativos]
      summary: Obter detalhes do aplicativo
      description: Retorna os detalhes de um aplicativo específico pelo seu ID, incluindo status do cadastro e das imagens.
      operationId: obterAplicativo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do aplicativo encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppDetalhado'
        '404':
          description: Aplicativo não encontrado.

  /apps/list:
    get:
      tags: [Aplicativos]
      summary: Listar aplicativos
      description: |
        Retorna uma lista paginada de aplicativos com dados resumidos (id, nome, status, data).
        Ideal para listagens e visão geral do estado dos cadastros.
      operationId: listarAplicativos
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Número da página
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Quantidade de itens por página
        - in: query
          name: status
          schema:
            type: string
            enum: [draft, pendente_upload, revisar, ativado, erro]
          description: Filtrar por status
        - in: query
          name: codigoParceiro
          schema:
            type: string
          description: Filtrar por código do parceiro
      responses:
        '200':
          description: Lista de aplicativos encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppListResponse'

components:
  schemas:
    AppDraftInput:
      type: object
      required:
        - nome
        - codigoParceiro
        - codigoProduto
      properties:
        nome:
          type: string
        descricao:
          type: string
        codigoParceiro:
          type: string
        codigoProduto:
          type: string
        contatoParceiro:
          $ref: '#/components/schemas/ContatoParceiro'
        categorias:
          type: array
          items:
            type: string
        configuracoes:
          type: array
          items:
            $ref: '#/components/schemas/ConfiguracaoAplicativoInput'
        detalheAplicativo:
          $ref: '#/components/schemas/DetalheAplicativoDraftInput'

    DetalheAplicativoDraftInput:
      type: object
      required:
        - descricao
      properties:
        descricao:
          type: string
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/ImagemMetadataInput'

    ImagemMetadataInput:
      type: object
      required:
        - nomeArquivo
        - tipoMime
        - tamanho
        - md5
      properties:
        nomeArquivo:
          type: string
        tipoMime:
          type: string
          description: Content-type da imagem
        tamanho:
          type: integer
          description: Tamanho da imagem em bytes
        md5:
          type: string
          description: Hash MD5 da imagem para validação

    ContatoParceiro:
      type: object
      required:
        - nome
        - email
        - telefone
      properties:
        nome:
          type: string
        email:
          type: string
        telefone:
          type: string
        descricao:
          type: string

    ConfiguracaoAplicativoInput:
      type: object
      required:
        - nomePacoteApp
        - tipoIntegracaoId
        - terminalModeloId
      properties:
        nomePacoteApp:
          type: string
        tipoIntegracaoId:
          type: string
        terminalModeloId:
          type: string

    AppDraftResponse:
      type: object
      required:
        - id
        - status
        - detalheAplicativo
      properties:
        id:
          type: string
        status:
          type: string
          enum: [draft, pendente_upload, revisar, ativado, erro]
        detalheAplicativo:
          $ref: '#/components/schemas/DetalheAplicativoDraftResponse'

    DetalheAplicativoDraftResponse:
      type: object
      required:
        - descricao
        - imagens
      properties:
        descricao:
          type: string
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/ImagemDraftResponse'

    ImagemDraftResponse:
      type: object
      required:
        - id
        - nomeArquivo
        - status
        - uploadUrl
      properties:
        id:
          type: string
        nomeArquivo:
          type: string
        tipoMime:
          type: string
          description: Content-type esperado da imagem
        tamanho:
          type: integer
          description: Tamanho da imagem em bytes
        md5:
          type: string
          description: Hash MD5 da imagem para validação
        status:
          type: string
          enum: [pendente_upload, upload_ok, erro]
        uploadUrl:
          type: string
          description: URL pré-assinada para upload da imagem

    AppDetalhado:
      type: object
      required:
        - id
        - nome
        - codigoParceiro
        - codigoProduto
        - status
      properties:
        id:
          type: string
        nome:
          type: string
        descricao:
          type: string
        codigoParceiro:
          type: string
        codigoProduto:
          type: string
        status:
          type: string
          enum: [draft, pendente_upload, revisar, ativado, erro]
          description: Status geral do cadastro
        contatoParceiro:
          $ref: '#/components/schemas/ContatoParceiro'
        categorias:
          type: array
          items:
            type: string
        configuracoes:
          type: array
          items:
            $ref: '#/components/schemas/ConfiguracaoAplicativoInput'
        detalheAplicativo:
          $ref: '#/components/schemas/DetalheAplicativoDraftResponse'
        criadoEm:
          type: string
          format: date-time
        atualizadoEm:
          type: string
          format: date-time

    AppListResponse:
      type: object
      required:
        - data
        - pagination
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AppResumo'
        pagination:
          $ref: '#/components/schemas/Pagination'

    AppResumo:
      type: object
      required:
        - id
        - nome
        - status
        - criadoEm
      properties:
        id:
          type: string
        nome:
          type: string
        codigoParceiro:
          type: string
        status:
          type: string
          enum: [draft, pendente_upload, revisar, ativado, erro]
        criadoEm:
          type: string
          format: date-time

    Pagination:
      type: object
      required:
        - page
        - pageSize
        - total
        - totalPages
      properties:
        page:
          type: integer
          description: Página atual
        pageSize:
          type: integer
          description: Itens por página
        total:
          type: integer
          description: Total de itens
        totalPages:
          type: integer
          description: Total de páginas
