name: CI Build & Test

on:
  push:
    branches: [main, master, develop, release, release/**]
  pull_request:
    branches: [main, master, develop, release, release/**]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: TypeScript Type Check
        run: npm run typecheck

      - name: ESLint Check
        run: npm run lint

      - name: Code Formatting Check
        run: npm run clang

      - name: Build TypeScript
        run: npm run build
